// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgesvcnwarjonxurtxny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnZXN2Y253YXJqb254dXJ0eG55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNzI1NjYsImV4cCI6MjA2NTk0ODU2Nn0.k6LGRB_sXRG2qGn65_pRmOCb901UCCxyliqP5gALX-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);